### PR TITLE
Update all scripts to node 18

### PR DESCRIPTION
**Pull request by gsnedders**
This uses nodegit@0.28.0-alpha.20, as they still haven't made a release that supports node >14 (https://github.com/nodegit/nodegit/issues/1840).

This trips people up from time-to-time (pretty much any time anyone new tries to contribute, and occasionally other times too), most recently see https://github.com/web-platform-tests/results-analysis/issues/138 (cc @karlcow).

This uses node 18 as it is the current LTS release, but this does appear to work locally on node 19.3.

### CODE REVIEW

**Comment by gsnedders** [comment]
Ah, default GitHub actions images don't have enough packages installed to build nodegit; need to make sure we actually install enough to get it to build…

**Comment by gsnedders** [comment]
> Ah, default GitHub actions images don't have enough packages installed to build nodegit; need to make sure we actually install enough to get it to build…

https://github.com/nodegit/nodegit/blob/master/.github/workflows/tests.yml contains:

```
        run: apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:git-core/ppa && apt-get update && apt-get install -y git build-essential clang libssl-dev libkrb5-dev libc++-dev wget
```

I suspect we can get away with a smaller subset (as we're not doing anything that requires up-to-date `git` for example), but it shows we do need a bunch…

**Comment by foolip** [comment]
@gsnedders if you can get the CI setup working for this, this would be great. It's indeed quite hard to contribute to this code right now because of the nodegit dependency...

**Comment by foolip** [comment]
This works for me locally, trying to get it landed now. The same change will be needed in https://github.com/web-platform-tests/results-analysis-cache/blob/main/.github/workflows/results.yml because that checks out this repo. (This setup is to avoid putting an access token in this repo to allow updating the cache.)

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
This all seems to have worked, thanks @gsnedders!

https://github.com/web-platform-tests/results-analysis-cache/actions/runs/4202276727 was the first run with the changes, and that pushed run/5119667887144960/results, an STP run. I compared that to the previous STP run with `git diff --stat run/5151119127347200/results run/5119667887144960/results` and there were only 94 files changed. The changes look like normal test results changes, nothing systemic that would suggest everything has blown up.

**Comment by foolip** [comment]
It also looks like the caching is working:
https://github.com/web-platform-tests/results-analysis-cache/actions/runs/4202387383/jobs/7290471863

**Pull request merged**
